/*
 * Copyright 2026 Dawson Hessler
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.brighten.antivpn.database.sql.utils;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Locale;

public enum SqlDialect {
    GENERIC,
    H2,
    MYSQL,
    POSTGRESQL;

    public static SqlDialect from(Connection connection) {
        if (connection == null) {
            return GENERIC;
        }

        try {
            String productName = connection.getMetaData().getDatabaseProductName();
            if (productName == null) {
                return GENERIC;
            }

            return from(productName);
        } catch (SQLException ignored) {
            return GENERIC;
        }
    }

    public static SqlDialect from(String productName) {
        String normalized = productName.toLowerCase(Locale.ROOT);
        if (normalized.contains("postgres")) {
            return POSTGRESQL;
        }
        if (normalized.contains("mysql")) {
            return MYSQL;
        }
        if (normalized.contains("h2")) {
            return H2;
        }
        return GENERIC;
    }

    public boolean isPostgreSql() {
        return this == POSTGRESQL;
    }

    public String translate(String sql) {
        if (!isPostgreSql()) {
            return sql;
        }

        String translated = sql.replace('`', '"');
        translated = translated.replaceAll(
                "(?i)\\bINT\\s+AUTO_INCREMENT\\s+PRIMARY\\s+KEY\\b",
                "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        );
        translated = translated.replaceAll("(?i)\\bAUTO_INCREMENT\\b", "GENERATED BY DEFAULT AS IDENTITY");
        translated = translated.replaceAll("(?i)\\bdouble\\b(?!\\s+precision)", "double precision");
        return translated;
    }
}
