#####################################################
#                  KauriVPN Config                  #
#              by Brighten Development              #
#####################################################
# If you find that you run out of your free 20,000 queries, you may purchase a license on https://funkemunky.cc/shop
license: ''
# Message only sent with commands disabled below. Supports color codes ('&')
kickMessage: Proxies are not allowed on our server
# Caching results will lower your query usage, but results may be out of date.
cachedResults: true
# All players with any of the following characters in the beginning of their name will be whitelisted
# This is a useful feature for servers that allow players through Geyser and their IPs are not forwarded, causing
# players to be removed falsely for use of proxy.
prefixWhitelists:
  - "*"
# Configure your database here.
database:
  # Enable to cache queries and save alerts state beyond restarts
  enabled: true
  useCredentials: false
  #Options Mongo, MySQL, or H2
  type: H2
  # The database name you would like to use
  database: kaurivpn
  # Can be used if you prefer to authenticate via Mongo URL
  mongoURL: ''
  # Your database username
  username: root
  # Your database password
  password: password
  # The IP of your database goes here
  ip: localhost
  # -1 will use default port of databases (MySQL:3306, Mongo:27017). Otherwise, enter alternative ports here.
  port: -1
commands:
  # Enable this to override the default kick function of the plugin with your own commands
  enabled: false
  # List of commands to run when a player is detected to be using a proxy. Supports color codes ('&')
  execute:
    - kick %player% VPNs are not allowed on our server!
# Enable/disable the default kicking feature of KauriVPN.
kickPlayers: true
# Configure all alerting functionality
alerts:
  # You may set to 'false' to disable all alerts functionality
  enabled: true
  # Message to send to users with alerts enabled
  # Placeholders: %country% (Country name), %player% (Player name), %reason% (Proxy detection method),
  # %city% (City name).
  message: '&8[&6KauriVPN&8] &e%player% &7has joined on a VPN/proxy &8(&f%reason%&8)
    &7in location &8(&f%city%&7, &f%country%&8)'
# Configuration for country gatekeepings
countries:
  # You must use ISO codes for country configuration: https://www.iban.com/country-codes
  # Leave empty to disable this configuration
  list: []
  # Set whitelist to true to only allow listed country codes, and false to deny listed country codes.
  whitelist: true
  # The commands to be run if the player is not allowed on the server with the above configured conditions
  # Placeholders: %country% (Country name), %player% (Player name), %code% (Country ISO Code)
  # Keep this empty with "[]" if you want to use the built in kicking system.
  commands: []
  # The kick message that will be used if commands are configured to use the built-in kicking sytem.
  # PlaceHolders: %country% (Country name), %player% (Player name), %code% (Country ISO Code)
  vanillaKickReason: |-
    &cSorry, but our server does not allow connections from
    &f%country%
# This will disable any information being sent to https://bstats.org. We recommend you keep this enabled as it helps
# us understand our users and put effort where it is needed. All information sent goes under their privacy as seen
# here: https://bstats.org/privacy-policy
bstats: true
# Here you can configure messages for KauriVPN.
messages:
  command-misc-playerRequired: '&cYou must be a player to execute this command!'
  command-alerts-toggled: '&7Your player proxy notifications have been set to: &e%state%'
  command-reload-complete: '&aSuccessfully reloaded KauriVPN plugin!'
  no-permission: '&cNo permission.'
